no change     /mnt/home/kocherov/anaconda3/condabin/conda
no change     /mnt/home/kocherov/anaconda3/bin/conda
no change     /mnt/home/kocherov/anaconda3/bin/conda-env
no change     /mnt/home/kocherov/anaconda3/bin/activate
no change     /mnt/home/kocherov/anaconda3/bin/deactivate
no change     /mnt/home/kocherov/anaconda3/etc/profile.d/conda.sh
no change     /mnt/home/kocherov/anaconda3/etc/fish/conf.d/conda.fish
no change     /mnt/home/kocherov/anaconda3/shell/condabin/Conda.psm1
no change     /mnt/home/kocherov/anaconda3/shell/condabin/conda-hook.ps1
no change     /mnt/home/kocherov/anaconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /mnt/home/kocherov/anaconda3/etc/profile.d/conda.csh
no change     /mnt/home/kocherov/.bashrc
No action taken.
trial 7
started
trial 7
generations 120
max body nodes 24
children 4
biases [0 1 2 3 4 5 6 7 8 9]
Traceback (most recent call last):
  File "/mnt/ufs18/home-220/kocherov/Documents/cgp/src/cgp.py", line 101, in <module>
    func = func_bank.func_list[int(argv[5])]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
